drop database if exists TRUONGHOC1;

-- tao csdl TRUONGHOC1
create database TRUONGHOC1;


--  dung csdl TRUONGHOC1
USE TRUONGHOC1;


-- tao bang TRUONG

CREATE TABLE TRUONG (
    MATR CHAR(6) PRIMARY KEY,
    TENTR VARCHAR(50) NOT NULL,
    DCHITR VARCHAR(256) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



-- tao bang HS

CREATE TABLE HS (
    MAHS char(9) PRIMARY KEY,  
    HO VARCHAR(50) NOT NULL,
    TEN VARCHAR(50) NOT NULL,
    CCCD VARCHAR(12),
    NTNS char(2) NOT NULL,
    DCHI_HS VARCHAR(100) NOT NULL,
    CONSTRAINT UQ_HS_CCCD UNIQUE (CCCD)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;





-- tao bang hoc
CREATE TABLE HOC (
    MATR char(9),
    MAHS char(9),
    NAMHOC char(9),
    DIEMTB char(2) NOT NULL,
    XEPLOAI varchar(20) NOT NULL,
    KQUA varchar(20) NOT NULL,
    PRIMARY KEY (MATR, MAHS, NAMHOC),
    FOREIGN KEY (MATR) REFERENCES TRUONG (MATR),
    FOREIGN KEY (MAHS) REFERENCES HS (MAHS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


